#!/usr/bin/env bash
#Configuring domain zone (snehadasa.tech) so that the subdomain www points to your
#load-balancer IP (lb-01) (34.73.212.78).

if [ "$#" -eq 2 ];then
	s=$2
else
	s=("www" "lb-01" "web-01" "web-02")
fi
for sd in "${s[@]}"
do
	dig "$sd.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print "The subdomain '$sd' is a " $4 " record and points to " $5}'
done
