#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# scp some_page.html 8.8.8.8 sylvain /vagrant/private_key

if [ "$#" -eq 4 ]
then
	scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3"@"$2":~/
else
	"Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
