#!/usr/bin/env bash
# to Install and configure HAproxy on your lb-01 server.

apt-get update
apt-get -y install haproxy
printf "\nfrontend Local_Server
	bind *:80 
	mode http
	default_backend My_Web_Servers
	
backend My_Web_Servers
	mode http
	balance roundrobin
	server 687-web1.local 35.229.72.201:80
	server 687-web2.local 35.237.176.253:80\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
